// Generated by CoffeeScript 1.9.1
var lineup, mockServer, refresh;

refresh = require('../lib/refresh');

lineup = require('../lib/lineup');

mockServer = require('./mockServer');

describe('refresh', function() {
  var $page, simulatePageNotBeingFound;
  simulatePageNotBeingFound = function() {
    return sinon.stub(jQuery, "ajax").yieldsTo('success', {
      title: 'asdf'
    });
  };
  $page = void 0;
  before(function() {
    $page = $('<div id="refresh" />');
    return $page.appendTo('body');
  });
  after(function() {
    return $page.empty();
  });
  it("creates a ghost page when page couldn't be found", function() {
    var key, pageObject;
    mockServer.simulatePageNotFound();
    $page.each(refresh.cycle);
    expect($page.hasClass('ghost')).to.be(true);
    expect(key = $page.data('key')).to.be.a('string');
    expect(pageObject = lineup.atKey(key)).to.be.an('object');
    return expect(pageObject.getRawPage().story[0].type).to.be('future');
  });
  return xit('should refresh a page', function(done) {
    simulatePageFound({
      title: 'asdf'
    });
    $page.each(refresh.cycle);
    jQuery.ajax.restore();
    expect($('#refresh h1').text()).to.be(' asdf');
    return done();
  });
});
