// Generated by CoffeeScript 1.9.1
var defaultargs;

defaultargs = require('../defaultargs');

describe('defaultargs', function() {
  return describe('#defaultargs()', function() {
    it('should not write over give args', function() {
      return defaultargs({
        port: 1234
      }).port.should.equal(1234);
    });
    it('should write non give args', function() {
      return defaultargs().port.should.equal(3000);
    });
    return it('should modify dependant args', function() {
      return defaultargs({
        data: '/tmp/asdf/'
      }).db.should.equal('/tmp/asdf/pages');
    });
  });
});
