// Generated by CoffeeScript 1.9.1
var bind, emit, neighborhood, resolve;

resolve = require('./resolve');

neighborhood = require('./neighborhood');

emit = function($item, item) {
  var i, info, len, ref, results;
  $item.append(item.text + "<br><br><button class=\"create\">create</button> new blank page");
  if (((info = neighborhood.sites[location.host]) != null) && (info.sitemap != null)) {
    ref = info.sitemap;
    results = [];
    for (i = 0, len = ref.length; i < len; i++) {
      item = ref[i];
      if (item.slug.match(/-template$/)) {
        results.push($item.append("<br><button class=\"create\" data-slug=" + item.slug + ">create</button> from " + (resolve.resolveLinks("[[" + item.title + "]]"))));
      } else {
        results.push(void 0);
      }
    }
    return results;
  }
};

bind = function($item, item) {};

module.exports = {
  emit: emit,
  bind: bind
};
