// Generated by CoffeeScript 1.9.1
var bind, dialog, editor, emit, resolve;

dialog = require('./dialog');

editor = require('./editor');

resolve = require('./resolve');

emit = function($item, item) {
  item.text || (item.text = item.caption);
  return $item.append("<img class=thumbnail src=\"" + item.url + "\"> <p>" + (resolve.resolveLinks(item.text)) + "</p>");
};

bind = function($item, item) {
  $item.dblclick(function() {
    return editor.textEditor($item, item);
  });
  return $item.find('img').dblclick(function() {
    return dialog.open(item.text, this);
  });
};

module.exports = {
  emit: emit,
  bind: bind
};
