// Generated by CoffeeScript 1.9.1
var bind, editor, emit, itemz, resolve;

editor = require('./editor');

resolve = require('./resolve');

itemz = require('./itemz');

emit = function($item, item) {
  var i, len, ref, results, text;
  ref = item.text.split(/\n\n+/);
  results = [];
  for (i = 0, len = ref.length; i < len; i++) {
    text = ref[i];
    if (text.match(/\S/)) {
      results.push($item.append("<p>" + (resolve.resolveLinks(text)) + "</p>"));
    } else {
      results.push(void 0);
    }
  }
  return results;
};

bind = function($item, item) {
  return $item.dblclick(function(e) {
    if (e.shiftKey) {
      item.type = 'html';
      return itemz.replaceItem($item, 'paragraph', item);
    } else {
      return editor.textEditor($item, item, {
        'append': true
      });
    }
  });
};

module.exports = {
  emit: emit,
  bind: bind
};
