// Generated by CoffeeScript 1.9.1
var itemId, randomByte, randomBytes;

randomByte = function() {
  return (((1 + Math.random()) * 0x100) | 0).toString(16).substring(1);
};

randomBytes = function(n) {
  return ((function() {
    var i, ref, results;
    results = [];
    for (i = 1, ref = n; 1 <= ref ? i <= ref : i >= ref; 1 <= ref ? i++ : i--) {
      results.push(randomByte());
    }
    return results;
  })()).join('');
};

itemId = function() {
  return randomBytes(8);
};

module.exports = {
  randomByte: randomByte,
  randomBytes: randomBytes,
  itemId: itemId
};
